apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nats-streaming-console
  name: nats-streaming-console
  namespace: nats-io
spec:
  ports:
  - name: http
    port: 8282
    protocol: TCP
    targetPort: 8282
  selector:
    app: nats-streaming-console
  type: ClusterIP
status:
  loadBalancer: {}